---
sudo: required
dist: trusty

language: python

python:
    - "3.4"
    - "3.5"

cache:
    directories:
        - bin
        - eggs

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev libxml2-dev libxslt1-dev libffi-dev

install:
    - python bootstrap.py
    - bin/buildout

script: bin/test
