---
 - hosts: all
   become: yes
   tasks:
       - name: install epel repository
         yum: name=epel-release state=present
       - name: install python dependencies
         yum: name={{ item }} state=present
         with_items:
             - python-pip
             - python34
             - python34-devel
             - openssl-devel
             - libffi-devel
             - libxml2-devel
             - libxslt-devel
             - make
             - gcc
       - name: install virtualenv
         pip: name=virtualenv state=present
       - name: install dorker # not a typo
         yum: name=docker state=present
       - name: start dorker # not a typo
         service: name=docker state=started enabled=yes
       - name: install workflow packages
         yum: name={{ item }} state=present
         with_items:
             # json parsing CLI
             - jq
             # bash completion
             - bash-completion
